### ISSUE TITLE
Problems in IE11 / Edge

### ISSUE THREAD

**Issue by l00mi** [zazuko/www.alod.ch#64]
It seems the there is somewhere in the newest libraries a to new JS functionality=

**Comment by StrubT** [comment]
Edge works
There are two syntax errors in IE – it does not support `class`es

I will try to find out where the class declarations come from.

**Comment by StrubT** [comment]
Great... I spent several hours looking into tcftest.org, which also doesn't work in IE for completely unrelated reasons... Will try spend some more time on this project over the weekend...

**Comment by l00mi** [comment]
You mentioned in Edge it works?

**Comment by StrubT** [comment]
Sorry, no. Will DM you with details.

**Comment by l00mi** [comment]
Edge -> problem seems to be bootstrap-tour
IE11 -> some other library

**Comment by StrubT** [comment]
WIP...

IE -> bootstrap-tour (`Unable to get property 'extend' of undefined or null reference`)
Edge -> CSS not loaded (`[CORS] The origin did not find in the Access-Control-Allow-Origin response header for cross-origin style resource at 'http://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/paper/bootstrap.min.css'.`)

**Comment by StrubT** [comment]
@l00mi After a lot of digging, I have finally found the root cause for this.
My proposed solution is to prepend all cdnjs.cloudflare.com URLs with https.
What do you think? Should I do the changes to alod & zack-search? Might other repositories be affected too?

**Comment by l00mi** [comment]
Please go ahead and do the changes for zack and alod. Will look for the rest later.

**Comment by StrubT** [comment]
added `https:`, `integrity` and `crossorigin="anonymous"` for every external `<link>` and `<script>` in both alod and zack-search

**Comment by StrubT** [comment]
There was a second error hidden inside zack-search. Tested. Works in both browsers now.

**Comment by StrubT** [comment]
concerning the second error: https://stackoverflow.com/a/37800329
