### ISSUE TITLE
change test.alod.ch to bar.alod.ch

### ISSUE THREAD

**Issue by l00mi** [zazuko/www.alod.ch#65]
- [ ] Change/add DNS entry.
- [ ] Change config of container -> DATASETBASEURL.
- [ ] Change config for traefik.

@ktk and @vhf could you please take care of this?

**Comment by vhf** [comment]
I added a DNS entry.

Here is the current traefik label on varnish, which means they serve alod: `HostRegexp: alod.ch, staatsarchiv-bs.ch, isil.ch, {subdomain:[A-Za-z0-9-.]+}.alod.ch, {subdomain:[A-Za-z0-9-.]+}.staatsarchiv-bs.ch, {subdomain:[A-Za-z0-9-.]+}.isil.ch`

Could you explain the 2nd point?

**Comment by l00mi** [comment]
Just scribbling, I am in a presentation currently:

- its the other stack. I think its called test-alod-ch
- the datasetbaseurl needs to match the domain name.. new bar.alod.ch <http://bar.alod.ch/>.. not sure if env var or inside the container, please check with @ktk

**Comment by l00mi** [comment]
Thank you!
