### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by tpluscode** [zazuko/www.alod.ch#79]
Please see why the certificate for data.alod.ch expired on June 11th and refresh

**Comment by sandhose** [comment]
The certificate failed to renew because we were requesting one for isil.ch but don't have the domain anymore. Fixed in https://github.com/zazuko/www.alod.ch/commit/e47f2c8dbb7e5bda8ec810d8f81f911d54ab7785
We also now have proper monitoring of certificates failing to renew
