### ISSUE TITLE
singleton object for query

### ISSUE THREAD

**Issue by l00mi** [zazuko/www.alod.ch#8]
It might be use full to have kind of a singleton object with the following overall info of the current result set:
- number of results
- the first and last result in time dimension (intervalStarts, intervalEnds) -> for timeline and time ticks
- evt. the histogram

I think finally we should have kind of two queries, one regarding the overall query (right know the count query) and than the paged queries.

**Comment by ktk** [comment]
Is that still a thing?

**Comment by l00mi** [comment]
hmm? nah was solved differently, why?

**Comment by ktk** [comment]
My bad showed up as open in Waffle, realized later that it was closed.
